Repository fe11-part4-team3/coworkers, pull requests merged in 2025-01, with the labels that each got.

#18 Feature/issue 14
  app/globals.css
  app/layout.tsx
  components/ModeToggle.tsx
  components/keep
  components/ui/button.tsx
  components/ui/dropdown-menu.tsx
  package-lock.json
  package.json
  tailwind.config.ts
  utils/theme-provider.tsx
Labels: ⚙ Setting

#20 API 함수 및 타입 구현 #17
  service/article.api.ts
  service/articleComment.api.ts
  service/auth.api.ts
  service/comment.api.ts
  service/group.api.ts
  service/image.api.ts
  service/oauth.api.ts
  service/recurring.api.ts
  service/task.api.ts
  service/taskList.api.ts
  service/user.api.ts
  types/article.type.ts
  types/articleComment.type.ts
  types/auth.type.ts
  types/comment.type.ts
  types/group.type.ts
  types/keep
  types/oauth.type.ts
  types/recurring.type.ts
  types/task.type.ts
  types/taskList.type.ts
  types/user.type.ts
Labels: ✨ Feature

#22 Feature/issue 19
  .vscode/settings.json
  app/layout.tsx
  app/page.tsx
  components/DarkmodeToggle.tsx
  components/ModeToggle.tsx
  components/layout/Container.tsx
  components/ui/ModeToggle.tsx
  eslint.config.mjs
  package-lock.json
  package.json
  tailwind.config.ts
  types/container.types.ts
Labels: ⚙ Setting

#29 shadcn 컴포넌트 install 시 tailwindcss 파일에서 플러그인 js 부분을 문자열로 자동 전환되는 이슈
  app/globals-custom.css
  app/globals.css
  app/layout.tsx
  eslint.config.mjs
  tailwind-custom.config.ts
  tailwind.config.ts
Labels: 🐞 BugFix

#37 로그인 기능 구현 axios instance
  app/login/page.tsx
  app/mypage/page.tsx
  app/page.tsx
  app/signup/page.tsx
  hooks/keep
  hooks/useAuth.ts
  hooks/useForm.ts
  hooks/useUserInfo.ts
  package-lock.json
  package.json
  service/auth.api.ts
  service/axios.ts
  service/user.api.ts
  store/useUser.store.ts
  styles/test.styles.ts
  types/auth.type.ts
Labels: ✨ Feature

#33 사이드 네비게이션 구현
  .prettierrc
  .vscode/settings.json
  app/[teamId]/page.tsx
  app/globals.css
  app/layout.tsx
  app/login/page.tsx
  app/mypage/page.tsx
  components/SideNavigation/GroupList.tsx
  components/SideNavigation/SideNavigation.tsx
  components/SideNavigation/SideNavigationTrigger.tsx
  components/SideNavigation/mockGroups.ts
  components/ui/input.tsx
  components/ui/separator.tsx
  components/ui/sheet.tsx
  components/ui/sidebar.tsx
  components/ui/skeleton.tsx
  components/ui/tooltip.tsx
  hooks/use-mobile.tsx
  package-lock.json
  package.json
  public/images/icon-close.svg
  public/images/icon-gnb-menu.svg
  public/images/keep
  tailwind.config.ts
  utils/keep
Labels: ✨ Feature, 🎨 Markup

#35 팀페이지의 그룹 헤더 구현
  app/[teamId]/GroupHeader.tsx
  public/images/icon-gear.svg
  public/images/img-thumbnail-team.png
Labels: ✨ Feature, 🎨 Markup

#36 zustand로 모달 구현, useClickOutside 커스텀 훅 제작
  app/[teamId]/tasklist/page.tsx
  components/Button.tsx
  components/modal/AddTaskList.tsx
  components/modal/InviteMember.tsx
  components/modal/ModalBase.tsx
  declarations.d.ts
  next.config.ts
  package-lock.json
  package.json
  stores/modalStore.ts
  types/modal.type.ts
  utils/useClickOutside.ts
Labels: ✨ Feature, 🎨 Markup

#46 TextareaField 컴포넌트 생성 / InputField 수정
  .storybook/main.ts
  .storybook/preview.ts
  components/InputField/ErrorMessage.tsx
  components/InputField/HideToggle.tsx
  components/InputField/InputField.tsx
  components/InputField/InputLabel.tsx
  components/InputField/TextareaField.tsx
  components/ui/textarea.tsx
  package-lock.json
  package.json
  stories/InputField/InputField.stories.tsx
  stories/Textarea/TextareaField.stories.tsx
  tsconfig.json
  types/inputField.type.ts
Labels: 🎨 Markup

#50 디바이스 타입 컨텍스트 및 디바운싱 커스텀 훅 구현
  app/layout.tsx
  contexts/DeviceTypeContext.tsx
  contexts/keep
  hooks/useDebounce.ts
Labels: ✨ Feature

#48 test 명령어 변경 제안 & catch error console.log 대신 사용 제안
  app/mypage/page.tsx
  components/TaskCard/TaskCard.tsx
  components/TaskCard/TaskCheckbox.tsx
  package.json
Labels: ⚙ Setting

#30 Nav Bar Ui 구현했습니다 (각종 버튼 및 드롭다운 X)
  app/layout.tsx
  components/layout/Container.tsx
  components/layout/Header/Headers.tsx
  components/layout/Header/Logo.tsx
  components/layout/Header/Profile.tsx
  declarations.d.ts
  public/images/codeitprofile.png
  public/images/img-BasicProfile.svg
  public/images/img-Check.svg
  public/images/img-Logo.svg
Labels: ✨ Feature, 🎨 Markup

#54 팀 페이지 멤버 프로필 구현
  app/[teamId]/page.tsx
  app/layout.tsx
  components/GroupMemberCard.tsx/GroupMemberCard.tsx
  components/SideNavigation/SideNavigation.tsx
  components/ui/avatar.tsx
  package-lock.json
  package.json
  public/images/icon-profile-member-default.svg
  public/images/icon-profile-member-write.svg
  types/group.type.ts
Labels: ✨ Feature, 🎨 Markup

#56 드롭다운 컴포넌트 제작
  app/globals-custom.css
  components/DropDown.tsx
  stories/DropDown.stories.tsx
Labels: 🎨 Markup

#44 할 일 카드 컴포넌트 재사용 확장
  components/TaskCard/IconLabel.tsx
  components/TaskCard/TaskCard.tsx
  components/TaskCard/TaskCheckbox.tsx
  components/TaskCard/Test.TaskCard.tsx
  components/ui/toast.tsx
  components/ui/toaster.tsx
  hooks/use-toast.ts
  package-lock.json
  package.json
  types/taskCard.type.ts
Labels: 🔨 Refactor, 🎨 Markup

#64 댓글 작성 textarea 컴포넌트
  components/CommentTextarea/CommentTextarea.tsx
  public/images/icon-enter.svg
  stories/CommentTextarea.stories.tsx
Labels: 🎨 Markup

#68 useForm hooks type update
  hooks/useForm.ts
Labels: 🐞 BugFix

#71 드롭다운 item 텍스트 추가
  components/DropDown.tsx
Labels: 🐞 BugFix, 🎨 Markup

#58 유저정보 Zustand 상태 초기화를 통해 API 중복 호출 방지
  app/addteam/page.tsx
  app/login/page.tsx
  app/mypage/page.tsx
  app/page.tsx
  app/signup/page.tsx
  components/GroupMemberCard.tsx/GroupMemberCard.tsx
  components/layout/Header/Headers.tsx
  components/layout/Header/Profile.tsx
  hooks/use-toast.ts
  hooks/useAuth.ts
  hooks/useUserInfo.ts
  service/axios.ts
  service/user.api.ts
  store/useUser.store.ts
  stores/useUser.store.ts
  types/inputField.type.ts
Labels: 🐞 BugFix, 🔨 Refactor, 🫠 pending

#69 할 일 카드 Dropdown, Storybook 추가
  app/globals-custom.css
  components/TaskCard/KebabButton.tsx
  components/TaskCard/TaskCard.tsx
  stories/TaskCard.stories.tsx
  types/taskCard.type.ts
Labels: 🎨 Markup

#63 VSCode 최적화 및 브랜치 생성 액션 수정
  .github/workflows/create-branch.yml
  .vscode/settings.json
Labels: 🐞 BugFix, ⚙ Setting

#60 글로벌 네비게이션 그룹 드롭다운 구현
  app/[teamId]/page.tsx
  components/GroupMemberCard.tsx/GroupMemberCard.tsx
  components/NavigationGroupDropdown/DropdownAddGroup.tsx
  components/NavigationGroupDropdown/DropdownTab.tsx
  components/NavigationGroupDropdown/NavigationGroupDropdown.tsx
  components/SideNavigation/mockGroups.ts
  components/layout/Header/Headers.tsx
  public/images/icon-arrow-down.svg
  public/images/icon-image-default.svg
  public/images/icon-plus.svg
Labels: 🎨 Markup

#78 로그인 완료시 헤더 리렌더링
  app/login/page.tsx
  app/mypage/page.tsx
  app/page.tsx
  app/signup/page.tsx
  components/layout/Header/Headers.tsx
  hooks/useAuth.ts
  styles/test.styles.ts
Labels: 🐞 BugFix

#88 globals-custom border 값 수정
  app/globals-custom.css
Labels: 🐞 BugFix, 🎨 Markup

#80 할 일 상세 댓글 (조회, 수정) 컴포넌트
  app/globals-custom.css
  components/DateDisplay.tsx
  components/IconLabel.tsx
  components/Profile.tsx
  components/TaskCard/DropdownButton.tsx
  components/TaskCard/TaskCard.tsx
  components/TaskCard/Test.TaskCard.tsx
  components/TaskDetailComment/CommentContent.tsx
  components/TaskDetailComment/TaskDetailComment.tsx
  stories/TaskDetailComment.stories.tsx
  utils/dateConversion.ts
Labels: 🎨 Markup

#65 버튼 컴포넌트
  app/globals-custom.css
  components/Button.tsx
  components/Buttons.tsx
  components/SelectBox.tsx
  components/modal/AddTaskList.tsx
  components/modal/InviteMember.tsx
  package-lock.json
  package.json
  public/images/icon-complete.svg
  stories/Buttons.stories.tsx
  tailwind.config.ts
  types/buttons.type.ts
  utils/filterClass.ts
Labels: 🎨 Markup

#90 🔥 Profile 중복 컴포넌트 제거
  components/Profile.tsx
  components/TaskDetailComment/TaskDetailComment.tsx
Labels: 🐞 BugFix

#83 팀 생성하기 기능 구현 및 store에 patch
  app/addteam/page.tsx
  types/group.type.ts
Labels: ✨ Feature

#82 프로필 컴포넌트 구현
  app/[teamId]/page.tsx
  components/GroupMemberCard/GroupMemberCard.tsx
  components/Profile/Profile.tsx
  public/images/icon-edit-small-light.svg
  public/images/icon-edit-small.svg
  public/images/icon-profile-image-light.svg
  public/images/icon-profile-image.svg
  public/images/icon-profile-member-default.svg
  public/images/icon-profile-member-light.svg
  public/images/icon-profile-member.svg
  stories/Profile.stories.ts
Labels: 🎨 Markup

#93 input color 시안과 다름 이슈
  app/globals-custom.css
  tailwind.config.ts
Labels: 🐞 BugFix, 🎨 Markup

#98 셀렉트 박스 props 변경
  app/globals-custom.css
  components/SelectBox.tsx
  stories/SelectBox.stories.ts
  tailwind.config.ts
  types/selectBox.type.ts
Labels: 🐞 BugFix

#104 #103 스타일 시트 네이밍 변경 및 정의
  .storybook/preview.ts
  app/layout.tsx
  styles/base.css
  styles/components.css
  styles/fonts.css
  styles/globals.css
  styles/utilities.css
  tailwind-pxr.config.ts
  tailwind.config.ts
Labels: 🎨 Markup, ⚙ Setting

#92 글로벌 헤더 네비게이션 구현
  app/[teamId]/page.tsx
  components/NavigationGroupDropdown/NavigationGroupDropdown.tsx
  components/SideNavigation/GroupList.tsx
  components/SideNavigation/SideNavigation.tsx
  components/layout/Header/Headers.tsx
  components/layout/Header/Profile.tsx
  components/ui/sidebar.tsx
  package-lock.json
  package.json
  public/images/icon-arrow-down.svg
  public/images/img-BasicProfile.svg
Labels: ✨ Feature, 🎨 Markup

#99 할 일 상세 댓글 컴포넌트 버튼, 프로필 적용
  components/Profile/Profile.tsx
  components/TaskDetailComment/CommentContent.tsx
  components/TaskDetailComment/TaskDetailComment.tsx
  components/TaskDetailComment/TaskDetailContent.tsx
  components/TaskDetailComment/TaskDetailFooter.tsx
  next.config.ts
Labels: 🎨 Markup

#94 자유게시판 베스트, 일반 게시글 카드 컴포넌트
  components/ArticleCard/ArticleCard.tsx
  components/ArticleCard/ArticleCardContent.tsx
  components/ArticleCard/ArticleCardFooter.tsx
  components/KebabDropDown.tsx
  components/LikeCount.tsx
  components/TaskCard/TaskCard.tsx
  components/TaskCard/TaskCardDropDown.tsx
  components/WriterProfile.tsx
  public/images/icon-heart.svg
  public/images/icon-medal.svg
  public/images/img-null.png
  stories/ArticleCard.stories.tsx
  styles/base.css
  styles/components.css
  utils/dateConversion.ts
Labels: 🎨 Markup

#113 📝 js doc 추가 및 import 경로 수정
  components/DateDisplay.tsx
  components/SearchInput/SearchInput.tsx
  components/TaskCard/TaskCard.tsx
  components/TaskCard/TaskCardDropDown.tsx
  components/TaskCard/TaskCheckbox.tsx
  components/TaskDetailComment/TaskDetailComment.tsx
  components/TaskDetailComment/TaskDetailContent.tsx
  components/TaskDetailComment/TaskDetailFooter.tsx
Labels: 📃 Docs

#117 #116 그룹 데이터 저장소와 관리를 위한 커스텀 훅 구현
  hooks/useGroup.ts
  stores/useGroup.stroe.ts
Labels: ✨ Feature

#119 자유게시판 게시글 상세 페이지 댓글 입력 textarea
  components/ArticleCommentTextarea/ArticleCommentTextarea.tsx
  components/TaskCommentTextarea/TaskCommentTextarea.tsx
  stories/ArticleCommentTextarea.stories.tsx
  stories/CommentTextarea.stories.tsx
  stories/TaskCommentTextarea.stories.tsx
Labels: 🎨 Markup

#126 #124 비밀번호 초기화 기능 구현
  app/login/page.tsx
  app/reset-password/page.tsx
  types/buttons.type.ts
  types/inputField.type.ts
Labels: ✨ Feature

#123 이미지 업로드 컴포넌트
  components/ArticleCard/ArticleCardFooter.tsx
  components/Comment/CommentContent.tsx
  components/ImageUpload/ImageUpload.tsx
  components/KebabDropDown.tsx
  components/NavigationGroupDropdown/DropdownAddGroup.tsx
  components/TaskCard/TaskCard.tsx
  public/images/icon-cancel.svg
  public/images/icon-plus.svg
  stories/imageUpload.stories.tsx
Labels: 🎨 Markup

#131 #130 네비게이션의 유저 드롭다운 구현
  components/layout/Header/Headers.tsx
Labels: ✨ Feature

#122 #115 마이페이지 프로필, 이름 수정 기능 구현
  app/addteam/page.tsx
  app/login/page.tsx
  app/mypage/page.tsx
  app/reset-password/page.tsx
  app/signup/page.tsx
  components/Buttons.tsx
  components/InputField/InputField.tsx
  components/Profile/Profile.tsx
  hooks/useForm.ts
  hooks/useGenericMutation.ts
  hooks/useUserLogic.ts
  service/image.api.ts
  service/user.api.ts
  types/buttons.type.ts
  types/inputField.type.ts
  utils/updatePayload.ts
Labels: ✨ Feature

#129 #105 팀 페이지 멤버 목록 구현
  app/[teamId]/(index)/GroupHeader.tsx
  app/[teamId]/(index)/GroupMemberCard.tsx
  app/[teamId]/(index)/GroupMemberList.tsx
  app/[teamId]/(index)/page.tsx
  app/[teamId]/page.tsx
  components/ImageUpload/ImageUpload.tsx
  components/NavigationGroupDropdown/DropdownAddGroup.tsx
  contexts/DeviceTypeContext.tsx
  public/images/icon-plus.svg
  stories/GroupMemberList.stories.tsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Markup

#121 할 일 상세 컴포넌트 제작
  app/[teamId]/tasklist/mockData.ts
  app/[teamId]/tasklist/page.tsx
  components/TaskDetail/TaskDetail.tsx
  package-lock.json
  package.json
  public/images/icon-calendar-button.svg
  public/images/icon-next-button.svg
  public/images/icon-prev-button.svg
  public/images/icon-task-check.svg
  types/task.type.ts
Labels: ✨ Feature, 🎨 Markup

#135 Feature/issue 134
  .vscode/settings.json
  app/[teamId]/(index)/GroupHeader.tsx
  app/[teamId]/(index)/GroupTaskList.tsx
  app/[teamId]/(index)/GroupTaskListWrapper.tsx
  app/[teamId]/(index)/TeamPage.type.ts
  app/[teamId]/(index)/page.tsx
  components/NavigationGroupDropdown/DropdownAddGroup.tsx
  stores/useGroup.stroe.ts
  styles/base.css
  types/group.type.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Markup

#110 커스텀 달력, 시계 제작
  app/[teamId]/tasklist/page.tsx
  components/DateTimePicker/DatePicker.tsx
  components/DateTimePicker/TimePicker.tsx
  components/layout/Header/Headers.tsx
  components/ui/calendar.tsx
  package-lock.json
  package.json
  public/images/icon-chevron-left.svg
  public/images/icon-chevron-right.svg
  stories/DatePicker.stories.tsx
  stories/TimePicker.stories.tsx
  styles/base.css
Labels: ✨ Feature, 🎨 Markup

#128 #127 로그인,회원가입 유효성 추가
  app/addteam/addteam.drawio
  app/addteam/page.tsx
  app/login/page.tsx
  app/mypage/page.tsx
  app/signup/page.tsx
  components/Buttons.tsx
  components/InputField/HideToggle.tsx
  hooks/useForm.ts
  hooks/useGenericMutation.ts
  hooks/useUserLogic.ts
  types/buttons.type.ts
  utils/validation.ts
Labels: ✨ Feature

#139 #138 버튼 컴포넌트 리팩토링
  app/login/page.tsx
  app/mypage/page.tsx
  app/reset-password/page.tsx
  components/ArticleCommentTextarea/ArticleCommentTextarea.tsx
  components/Buttons.tsx
  components/Comment/CommentFooter.tsx
  components/InputField/InputField.tsx
  components/modal/AddList.tsx
  components/modal/AddTask.tsx
  components/modal/AddTaskList.tsx
  components/modal/AddTeam.tsx
  components/modal/ChangePassword.tsx
  components/modal/DeleteAccount.tsx
  components/modal/DeleteTask.tsx
  components/modal/InviteMember.tsx
  components/modal/Logout.tsx
  components/modal/MemberProfile.tsx
  components/modal/ResetPassword.tsx
  stories/Buttons.stories.tsx
  styles/base.css
  types/buttons.type.ts
Labels: 🔨 Refactor, 🎨 Markup

#137 #136 팀 페이지 그룹 헤더 테마 스타일 및 드롭다운 구현
  app/[teamId]/(index)/GroupHeader.tsx
  components/Profile/Profile.tsx
  hooks/useThemeMode.ts
  public/images/icon-gear.svg
  public/images/img-thumbnail-team-light.png
  styles/base.css
  tailwind.config.ts
Labels: 🎨 Markup

#140 #132 프로필 컴포넌트 리팩토링
  app/[teamId]/(index)/GroupMemberCard.tsx
  app/addteam/page.tsx
  app/mypage/page.tsx
  components/Profile/IconEdit.tsx
  components/Profile/IconProfile.tsx
  components/Profile/Profile.tsx
  components/modal/MemberProfile.tsx
  hooks/useFileHandler.ts
  hooks/useForm.ts
  stories/Profile.stories.ts
  types/user.type.ts
  utils/updatePayload.ts
Labels: 🔨 Refactor

#143 자유게시판 리스트 페이지
  app/boards/AddArticleButton.tsx
  app/boards/ArticleList.tsx
  app/boards/ArticleSearch.tsx
  app/boards/ArticleSkeleton.tsx
  app/boards/BestArticleList.tsx
  app/boards/EmptyList.tsx
  app/boards/[articleId]/page.tsx
  app/boards/addarticle/page.tsx
  app/boards/page.tsx
  components/ArticleCard/ArticleCard.tsx
  components/ArticleCard/ArticleCardContent.tsx
  components/layout/Container.tsx
  components/layout/Header/Headers.tsx
  hooks/useGetArticle.ts
  next.config.ts
  public/images/img-noTeam.png
Labels: ✨ Feature, 🎨 Markup

#142 #141 간편로그인 컴포넌트
  components/OauthForm.tsx
  public/images/icon-google.svg
  public/images/icon-kakao.svg
  stories/OauthForm.stories.tsx
  styles/components.css
Labels: 🎨 Markup

#147 할 일 목록 배열 관리 커스텀 훅 구현
  app/[teamId]/(index)/GroupTaskList.tsx
  app/[teamId]/(index)/GroupTaskListWrapper.tsx
  app/[teamId]/(index)/page.tsx
  hooks/useGroup.ts
  hooks/useTaskLists.ts
  service/taskList.api.ts
  stores/useGroup.store.ts
  types/taskList.type.ts
Labels: ✨ Feature
