Repository fe11-part4-team3/coworkers, pull requests merged in 2025-02, with the labels that each got.

#149 #148 버튼 컴포넌트 props 수정
  app/boards/AddArticleButton.tsx
  app/mypage/page.tsx
  components/ArticleCommentTextarea/ArticleCommentTextarea.tsx
  components/Buttons.tsx
  components/Comment/CommentFooter.tsx
  components/InputField/InputField.tsx
  types/buttons.type.ts
Labels: 🐞 BugFix

#151 #150 프로필 컴포넌트 에러메세지 및 라벨 추가
  components/Profile/Profile.tsx
  hooks/useFileHandler.ts
  hooks/useForm.ts
Labels: 🐞 BugFix

#153 #152 Container 컴포넌트 pt에서 mt으로 변경
  components/layout/Container.tsx
Labels: 🐞 BugFix, 🎨 Markup

#155 #154 로그인,회원가입,팀생성&추가, 비밀번호 재설정 UI
  app/(auth)/addteam/addteam.drawio
  app/(auth)/addteam/page.tsx
  app/(auth)/jointeam/page.tsx
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/reset-password/page.tsx
  app/(auth)/signup/page.tsx
  app/login/page.tsx
  components/NavigationGroupDropdown/DropdownAddGroup.tsx
  components/NavigationGroupDropdown/NavigationGroupDropdown.tsx
  components/layout/Header/Headers.tsx
  components/modal/ResetPassword.tsx
  components/ui/dropdown-menu.tsx
  stories/modal.stories.tsx
  styles/components.css
Labels: 🎨 Markup

#161 #160 팀페이지 할 일 목록 클릭 시 리다이렉트 구현
  app/[teamId]/(index)/GroupTaskList.tsx
Labels: ✨ Feature

#157 #156 마이페이지 UI 및 회원탈퇴 모달 연결
  app/mypage/page.tsx
  components/InputField/InputField.tsx
  components/modal/ChangePassword.tsx
  components/modal/DeleteAccount.tsx
  public/images/icon-secession.svg
  stories/modal.stories.tsx
  types/inputField.type.ts
Labels: 🎨 Markup

#174 새로고침 시 리다이렉트 되는 문제를 해결
  hooks/useUser.ts
Labels: 🐞 BugFix

#169 오늘의 진행 상황 차트 구현
  app/[teamId]/(index)/GroupReports.tsx
  app/[teamId]/(index)/charts/TodayProgressChart.tsx
  app/[teamId]/(index)/page.tsx
  components/ui/chart.tsx
  package-lock.json
  package.json
  stories/TodayProgressChart.stories.tsx
Labels: ✨ Feature, 🎨 Markup

#166 자유게시판 게시글 상세 페이지
  app/boards/ArticleList.tsx
  app/boards/ArticleSearch.tsx
  app/boards/BestArticleList.tsx
  app/boards/[articleId]/ArticleDetail.tsx
  app/boards/[articleId]/ArticleDetailSkeleton.tsx
  app/boards/[articleId]/CommentContainer.tsx
  app/boards/[articleId]/page.tsx
  components/ArticleCard/ArticleCard.tsx
  components/Comment/Comment.tsx
  components/Comment/CommentContent.tsx
  components/Comment/CommentFooter.tsx
  components/Comment/CommentSkeleton.tsx
  components/IconLabel.tsx
  components/LikeCount.tsx
  components/TaskCard/TaskCard.tsx
  service/article.api.ts
  service/articleComment.api.ts
  service/axios.ts
  stories/Comment.stories.tsx
  types/comment.type.ts
  types/taskCard.type.ts
Labels: ✨ Feature, 🎨 Markup

#177 자유게시판 리스트 페이지 게시글 삭제 기능
  app/boards/ArticleList.tsx
  components/ArticleCard/ArticleCard.tsx
  components/ArticleCard/ArticleCardContent.tsx
  hooks/useGetArticle.ts
Labels: ✨ Feature

#168 자유게시판 게시글 생성 페이지
  app/boards/[articleId]/CommentContainer.tsx
  app/boards/addarticle/page.tsx
  components/ArticleCard/ArticleCard.tsx
  components/Comment/CommentContent.tsx
  components/ImageUpload/ImageUpload.tsx
  hooks/useFileHandler.ts
  hooks/useForm.ts
  hooks/useGetArticle.ts
  stories/imageUpload.stories.tsx
Labels: ✨ Feature, 🎨 Markup

#188 #187 스낵바 컴포넌트 제작
  app/(auth)/login/page.tsx
  app/layout.tsx
  components/SnackBar/SnackBar.hook.ts
  components/SnackBar/SnackBar.styled.tsx
  components/SnackBar/SnackBar.type.ts
  components/layout/Header/Headers.tsx
  contexts/SnackBar.context.tsx
  public/images/icon-state-done-white.svg
  stories/SnackBar.stories.tsx
Labels: ✨ Feature, 🎨 Markup

#182 #180 데이터없음 화면 및 404 페이지
  app/404/NotFound.tsx
  app/[teamId]/(index)/page.tsx
  app/boards/ArticleList.tsx
  app/boards/EmptyList.tsx
  app/page.tsx
  components/Empty/Empty.tsx
  components/Empty/Empty.type.ts
  stories/Empty.stories.tsx
Labels: ✨ Feature, 🎨 Markup

#183 #181 팀페이지 리포트 컴포넌트 구현
  app/[teamId]/(index)/GroupReport.tsx
  app/[teamId]/(index)/GroupReportContent.tsx
  app/[teamId]/(index)/GroupReports.tsx
  app/[teamId]/(index)/GroupSwitch.tsx
  app/[teamId]/(index)/charts/TodayProgressChart.tsx
  app/[teamId]/(index)/page.tsx
  app/layout.tsx
  components/ui/carousel.tsx
  components/ui/chart.tsx
  components/ui/label.tsx
  components/ui/switch.tsx
  package-lock.json
  package.json
  public/images/icon-chart-pie.svg
  public/images/icon-report-done.svg
  public/images/icon-report-todo.svg
  public/images/icon-text-box-outline.svg
  stories/GroupReport.stories.tsx
Labels: ✨ Feature, 🎨 Markup

#185 #184 팀페이지 권한 제한 구현
  app/[teamId]/(index)/GroupHeader.tsx
  app/[teamId]/(index)/GroupMemberCard.tsx
  app/[teamId]/(index)/GroupMemberList.tsx
  app/[teamId]/(index)/GroupTaskList.tsx
  app/[teamId]/(index)/GroupTaskListWrapper.tsx
  app/[teamId]/(index)/page.tsx
  stories/GroupMemberList.stories.tsx
  types/group.type.ts
Labels: ✨ Feature

#191 #190 화살표 툴팁 제작
  app/mypage/page.tsx
  components/ArrowTooltip.tsx
  components/InputField/ErrorMessage.tsx
  components/InputField/InputField.tsx
  components/Profile/Profile.tsx
  hooks/useFadeComponents.ts
  stories/ArrowTooltip.stories.tsx
  stories/InputField.stories.tsx
  styles/components.css
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Markup

#193 #192 1차 QA 반영 및 input 디바운스 적용
  app/(auth)/signup/page.tsx
  app/mypage/page.tsx
  contexts/DeviceTypeContext.tsx
  hooks/useDebounce.ts
  hooks/useForm.ts
Labels: 🐞 BugFix, ✨ Feature

#189 게시글 상세 페이지 댓글 리스트 무한스크롤
  app/boards/[articleId]/CommentContainer.tsx
  components/Comment/CommentContent.tsx
  hooks/useIntersectionObserver.ts
  package-lock.json
  package.json
  types/articleComment.type.ts
Labels: ✨ Feature

#197 #196 버튼 loading시 로딩스피너만 노출
  components/Buttons.tsx
Labels: 🎨 Markup

#201 #200 팀페이지 조건 분기
  app/[teamId]/(index)/page.tsx
  components/layout/Header/Headers.tsx
Labels: 🐞 BugFix

#202 자유게시판 리스트 페이지 개선
  app/boards/ArticleList.tsx
  app/boards/ArticleSearch.tsx
  app/boards/BestArticleList.tsx
  app/boards/page.tsx
  components/ArticleCard/ArticleCard.tsx
  components/ArticleCard/ArticleCardContent.tsx
  components/ArticleCard/HighLight.tsx
  package-lock.json
  package.json
Labels: ✨ Feature, 🎨 Markup

#206 #205 로그아웃 시 스토어 및 캐싱 지우기
  components/layout/Header/Headers.tsx
  components/modal/Logout.tsx
  stories/modal.stories.tsx
Labels: ✨ Feature

#204 #203 URL 문자열 생성 함수 구현 및 할 일 목록 이동 경로 수정
  app/[teamId]/(index)/GroupTaskList.tsx
  utils/createUrlString.ts
Labels: 🐞 BugFix, ✨ Feature

#210 #207 마이히스토리 페이지 UI 작업
  app/myhistory/mock.json
  app/myhistory/page.tsx
Labels: 🎨 Markup

#214 #212 사이드 네비게이션 자유게시판 경로 수정
  components/SideNavigation/SideNavigation.tsx
Labels: 🐞 BugFix

#159 메인 렌딩페이지 작업했습니다.
  app/myhistory/fetchCompletedTasks.tsx
  app/page.tsx
  components/Landing/Iconbox.tsx
  components/Landing/Imagebox.tsx
  components/Landing/LandingCard.tsx
  components/Landing/LandingCardItemsFirst.tsx
  components/Landing/LandingCardItemsSecond.tsx
  components/Landing/LandingCardItemsthird.tsx
  components/Landing/LandingCardList.tsx
  public/images/landing/icon-Tool.svg
  public/images/landing/icon-check.svg
  public/images/landing/icon-folder.svg
  public/images/landing/icon-message.svg
  public/images/landing/img-Landing-bg-mo.png
  public/images/landing/img-Landing-bg-ta.png
  public/images/landing/img-Landing-bg.png
  public/images/landing/img-Landing-bottom-mo.png
  public/images/landing/img-Landing-bottom-ta.png
  public/images/landing/img-Landing-bottom.png
  public/images/landing/img-LandingCardimgfirst.png
  public/images/landing/img-LandingCardimgsecond.png
  public/images/landing/img-LandingCardimgthird.png
  stories/LandingCardList.stories.tsx
  tailwind.config.ts
Labels: 🎨 Markup

#216 #215 useForm의 changedFields, errorMessage 초기화 로직 변경
  hooks/useForm.ts
Labels: 🐞 BugFix

#225 #224 DarkmodeToggle에 useThemeMode 적용
  app/(auth)/addteam/page.tsx
  app/(auth)/jointeam/page.tsx
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/reset-password/page.tsx
  app/(auth)/signup/page.tsx
  app/[teamId]/(index)/GroupHeader.tsx
  app/layout.tsx
  app/mypage/page.tsx
  components/DarkmodeToggle.tsx
  components/InputField/InputField.tsx
  components/OauthForm.tsx
  components/modal/DeleteAccount.tsx
  components/modal/ResetPassword.tsx
  hooks/useForm.ts
  hooks/useKakao.ts
  hooks/useThemeMode.ts
  stories/modal.stories.tsx
  types/inputField.type.ts
Labels: 🐞 BugFix

#219 📝 alert -> 스낵바 적용 및 댓글 스크롤 애니메이션 추가
  app/boards/ArticleList.tsx
  app/boards/[articleId]/ArticleDetail.tsx
  app/boards/[articleId]/CommentContainer.tsx
  app/boards/addarticle/page.tsx
  app/boards/editarticle/[articleId]/page.tsx
  components/Comment/Comment.tsx
  components/IconLabel.tsx
  components/modal/EditDelete.tsx
Labels: 🔨 Refactor

#218 #211 팀페이지의 팀 수정하기 기능 구현
  app/[teamId]/(index)/GroupEditModal.tsx
  app/[teamId]/(index)/GroupHeader.tsx
  app/[teamId]/(index)/TeamPage.type.ts
  app/[teamId]/(index)/page.tsx
Labels: ✨ Feature, 🎨 Markup

#222 #198 다크모드 토글 위치 및 디자인 수정
  app/[teamId]/(index)/GroupHeader.tsx
  app/layout.tsx
  components/DarkmodeToggle.tsx
  components/layout/Header/Headers.tsx
  hooks/useThemeMode.ts
Labels: 🔨 Refactor

#227 #226 useParams 구조분해할당 경고문 및 Image 컴포넌트 경고문 에러 수정
  app/[teamId]/(index)/page.tsx
  app/boards/[articleId]/page.tsx
  app/boards/editarticle/[articleId]/page.tsx
  components/Empty/Empty.tsx
  components/layout/Header/Headers.tsx
  components/layout/Header/Logo.tsx
Labels: 🐞 BugFix

#236 #221 input 정상 입력 시에도 툴팁이 노출되는 버그 수정
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  components/InputField/InputField.tsx
  hooks/useForm.ts
Labels: 🐞 BugFix

#242 팀페이지에 멤버가 아닌 사용자가 접속이 가능한 문제 해결
  app/[teamId]/layout.tsx
Labels: 🐞 BugFix

#235 #230 팀 삭제하기 기능 구현
  app/[teamId]/(index)/GroupDeleteModal.tsx
  app/[teamId]/(index)/GroupHeader.tsx
  app/[teamId]/(index)/page.tsx
  hooks/useTaskLists.ts
  service/group.api.ts
  types/group.type.ts
Labels: ✨ Feature, 🎨 Markup

#243 페이지별 Head Title 적용
  app/favicon.ico
  app/layout.tsx
  components/DynamicTitle.tsx
Labels: 📃 Docs

#245 자유게시판 리스트 페이지 테블릿, 모바일 해상도 UI 틀어짐 수정
  app/boards/ArticleList.tsx
Labels: 🐞 BugFix

#238 할 일 카드(마이 히스토리) 토스트 메시지를 스낵바로 교체
  components/TaskCard/TaskCheckbox.tsx
  components/ui/toast.tsx
  components/ui/toaster.tsx
  hooks/use-toast.ts
Labels: 🔨 Refactor

#248 #231 멤버 초대하기 기능 구현
  app/[teamId]/(index)/GroupMemberList.tsx
  components/modal/InviteMember.tsx
  stories/modal.stories.tsx
  utils/createUrlString.ts
Labels: ✨ Feature

#223 마이히스토리 api 함수 호출 및 리스트 또는 빈 배열 반환
  app/myhistory/fetchCompletedTasks.tsx
  app/myhistory/mock.json
  app/myhistory/page.tsx
  service/user.api.ts
Labels: ✨ Feature

#249 #237 useUser,useUserStore 리팩토링
  app/(auth)/login/page.tsx
  components/OauthForm.tsx
  hooks/useUser.ts
  stores/useUser.store.ts
Labels: 🔨 Refactor

#251 #250 GNB 드롭다운 개선
  components/NavigationGroupDropdown/AddTeamModal.tsx
  components/NavigationGroupDropdown/DropdownAddGroup.tsx
  components/NavigationGroupDropdown/DropdownTab.tsx
  components/NavigationGroupDropdown/NavigationGroupDropdown.tsx
Labels: ✨ Feature, 🎨 Markup

#255 ✨ 스크롤 애니메이션 Container 컴포넌트에 적용
  app/boards/page.tsx
  components/layout/Container.tsx
Labels: 🎨 Markup

#252 #241 팀초대 query token으로 받아서 리다이렉트 기능 추가
  app/(auth)/jointeam/page.tsx
  app/(auth)/login/page.tsx
Labels: ✨ Feature

#259 #258 로그인 페이지 접근성,SEO 최적화
  app/layout.tsx
  components/DarkmodeToggle.tsx
  components/InputField/HideToggle.tsx
  styles/fonts.css
Labels: 🥰 Accessibility

#257 #254 헤더 디테일 수정 및 리팩토링
  components/SideNavigation/SideNavigation.tsx
  components/layout/Header/Headers.tsx
  components/layout/Header/HeadersGnb.tsx
  components/layout/Header/HeadersProfileDropDown.tsx
  components/layout/Header/HeadersSideNav.tsx
  components/layout/Header/Logo.tsx
  components/layout/Header/Profile.tsx
Labels: 🔨 Refactor, 🎨 Markup

#260 #233 멤버 상세 정보 모달 및 멤버 삭제 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  app/[teamId]/(index)/DeleteMemberModal.tsx
  app/[teamId]/(index)/GroupMemberCard.tsx
  app/[teamId]/(index)/GroupMemberList.tsx
  app/[teamId]/(index)/GroupTaskList.tsx
  app/[teamId]/(index)/TeamPage.type.ts
  app/[teamId]/(index)/page.tsx
  components/KebabDropDown.tsx
  components/modal/MemberProfile.tsx
  stories/modal.stories.tsx
Labels: ✨ Feature, 🎨 Markup

#263 #262 useGroup 리팩토링
  app/[teamId]/(index)/page.tsx
  app/[teamId]/layout.tsx
  app/boards/[articleId]/page.tsx
  app/boards/editarticle/[articleId]/page.tsx
  components/DynamicTitle.tsx
  components/layout/Header/Headers.tsx
  components/layout/Header/HeadersGnb.tsx
  components/layout/Header/HeadersProfileDropDown.tsx
  hooks/useGroup.ts
  hooks/useSafeParams.ts
Labels: 🔨 Refactor

#275 #271 할일 생성 버튼 마크업 수정
  app/[teamId]/[taskId]/page.tsx
Labels: 🐞 BugFix

#287 #286 => #284 할일 추가 버튼 수정
  app/[teamId]/tasklist/page.tsx
Labels: 🐞 BugFix, 🎨 Markup

#280 할 일 상세 수정
  components/TaskDetail/TaskDetail.tsx
Labels: 🔨 Refactor, 🎨 Markup

#291 #289 할 일 리스트 페이지 커스텀 훅 적용
  app/[teamId]/tasklist/page.tsx
  hooks/useTaskLists.ts
  stories/modal.stories.tsx
Labels: ✨ Feature, 🔨 Refactor

#293 #288 => #284 AddTask 모달 API POST 및 DatePicker 수정
  components/DateTimePicker/DatePicker.tsx
  components/DateTimePicker/RecurringDay.tsx
  components/SelectBox.tsx
  components/modal/AddTask.tsx
  hooks/useForm.ts
  hooks/useTaskLists.ts
  hooks/useTaskMutation.ts
  stories/DatePicker.stories.tsx
  types/useForm.type.ts
  utils/updatePayload.ts
Labels: 🐞 BugFix, 🔨 Refactor

#297 #296 할 일 추가 모달 렌더링 시 불필요한 요청을 보내던 오류 해결
  app/[teamId]/(index)/page.tsx
  app/[teamId]/tasklist/page.tsx
  components/modal/AddTask.tsx
  hooks/useDate.ts
  hooks/useTaskLists.ts
  hooks/useTaskMutation.ts
  stores/useDateStore.ts
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#281 #278 사이드바 스타일링 및 구조변경
  components/SideNavigation/GroupList.tsx
  components/SideNavigation/SideNavDefaultList.tsx
  components/SideNavigation/SideNavGroupLabel.tsx
  components/SideNavigation/SideNavTeamList.tsx
  components/SideNavigation/SideNavigation.tsx
  components/SideNavigation/mockGroups.ts
  components/ui/sheet.tsx
  components/ui/sidebar.tsx
  styles/utilities.css
  tailwind.config.ts
Labels: 🔨 Refactor, 🎨 Markup

#298 #284 할 일 리스트 페이지
  app/[teamId]/(index)/page.tsx
  app/[teamId]/[taskId]/page.tsx
  app/[teamId]/tasklist/mockData.ts
  app/[teamId]/tasklist/page.tsx
  app/boards/[articleId]/CommentContainer.tsx
  app/myhistory/mock.json
  components/Comment/Comment.tsx
  components/DateTimePicker/DatePicker.tsx
  components/DateTimePicker/RecurringDay.tsx
  components/SelectBox.tsx
  components/TaskCard/TaskCard.tsx
  components/TaskDetail/TaskDetail.tsx
  components/modal/AddTask.tsx
  hooks/useDate.ts
  hooks/useForm.ts
  hooks/useModalForm.tsx
  hooks/useTaskLists.ts
  hooks/useTaskMutation.ts
  package-lock.json
  package.json
  public/images/icon-chevron-left.svg
  public/images/icon-chevron-right.svg
  public/images/icon-task-check.svg
  service/comment.api.ts
  service/task.api.ts
  stores/useDateStore.ts
  stories/DatePicker.stories.tsx
  stories/modal.stories.tsx
  types/comment.type.ts
  types/task.type.ts
  types/taskCard.type.ts
  types/useForm.type.ts
  utils/updatePayload.ts
Labels: ✨ Feature, 🎨 Markup

#302 💄 댓글 수정하기 버튼 텍스트 색상 추가
  components/Comment/CommentFooter.tsx
Labels: 🎨 Markup

#290 코드 가독성 향상
  app/boards/ArticleList.tsx
  app/boards/ArticleSearch.tsx
  app/boards/ArticleSkeleton.tsx
  app/boards/[articleId]/ArticleDetail.tsx
  app/boards/[articleId]/CommentContainer.tsx
  app/boards/addarticle/page.tsx
  app/boards/editarticle/[articleId]/page.tsx
  app/boards/page.tsx
  components/ArticleCard/ArticleCard.tsx
  components/ArticleCard/ArticleCardContent.tsx
  components/ArticleCard/ArticleCardFooter.tsx
  components/ArticleCard/HighLight.tsx
  components/Comment/Comment.tsx
  components/Comment/CommentContent.tsx
  components/Comment/CommentFooter.tsx
  components/DateDisplay.tsx
  components/ImageUpload/ImageUpload.tsx
  components/LikeCount.tsx
  components/SearchInput/SearchInput.tsx
  components/TaskCard/TaskCard.tsx
  components/TaskCard/TaskCheckbox.tsx
  components/TaskCommentTextarea/TaskCommentTextarea.tsx
  components/WriterProfile.tsx
  styles/components.css
  types/article.type.ts
  types/articleComment.type.ts
Labels: 📃 Docs, 🔨 Refactor

#300 #299 2차QA alert 스낵바로 교체
  components/OauthForm.tsx
  components/modal/ChangePassword.tsx
  service/auth.api.ts
  service/axios.ts
  stores/useUser.store.ts
  utils/updatePayload.ts
Labels: 🐞 BugFix

#306 #305 2차QA 14번 이슈 수정 - 비밀번호,비밀번호확인 정상 입력후 다시 비밀번호를 변경할때 버튼활성화 되는 이슈
  app/(auth)/reset-password/page.tsx
  app/(auth)/signup/page.tsx
  components/modal/ChangePassword.tsx
  hooks/useForm.ts
  hooks/useInputFieldHandler.ts
  utils/validation.ts
Labels: 🐞 BugFix

#307 #303 할 일 상세 컴포넌트 개선
  app/[teamId]/tasklist/TaskListWrapper.tsx
  app/[teamId]/tasklist/page.tsx
  components/ui/drawer.tsx
  package-lock.json
  package.json
  tailwind.config.ts
  utils/validation.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Markup

#309 #308 할 일 상세의 댓글 수정 및 삭제 기능 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  app/[teamId]/tasklist/TaskListWrapper.tsx
  app/[teamId]/tasklist/page.tsx
  components/SnackBar/SnackBar.styled.tsx
Labels: ✨ Feature

#313 #312 할일 리스트 2차 QA 반영
  app/[teamId]/tasklist/TaskListWrapper.tsx
  app/[teamId]/tasklist/page.tsx
Labels: 🐞 BugFix, 🎨 Markup

#314 게시글 수정페이지 Preview 미노출 이슈
  app/boards/editarticle/[articleId]/page.tsx
  components/ImageUpload/ImageUpload.tsx
  hooks/useFileHandler.ts
  reducer/formReducer.ts
  types/useForm.type.ts
  utils/updatePayload.ts
Labels: 🐞 BugFix

#316 #315 할일 리스트 캘린더 추가
  app/[teamId]/tasklist/page.tsx
  components/DateTimePicker/DatePicker.tsx
  components/modal/AddTask.tsx
  components/ui/calendar.tsx
  hooks/useDate.ts
  hooks/useToggle.tsx
Labels: 🐞 BugFix, ✨ Feature

#317 #310 할 일 수정 및 삭제 구현
  app/[teamId]/tasklist/TaskCommentWrapper.tsx
  app/[teamId]/tasklist/TaskListWrapper.tsx
Labels: ✨ Feature

#324 #323 드롭다운 클릭 후 닫히지 않는 문제 해결
  components/layout/Header/HeadersProfileDropDown.tsx
Labels: 🐞 BugFix

#319 #318 팀참여,팀생성,로그인,패스워드 재설정
  app/(auth)/layout.tsx
  components/InputField/HideToggle.tsx
  components/layout/Container.tsx
Labels: 🎨 Markup

#285 🎨 useQuery 사용으로 myhistory api 호출 함수 최적화
  app/myhistory/mock.json
  app/myhistory/page.tsx
Labels: 🔨 Refactor

#328 #327 할일 추가 모달에서 이전 날짜 선택 시 경고 스낵바 추가
  components/DateTimePicker/DatePicker.tsx
  components/modal/AddTask.tsx
Labels: 🐞 BugFix, 🎨 Markup

#330 #329 메인 랜딩 QA 반영(bg컬러 및 라이트모드)
  app/page.tsx
  components/Landing/LandingCardItemsthird.tsx
  styles/base.css
  tailwind.config.ts
Labels: 🐞 BugFix, 🎨 Markup

#326 #325 팀페이지 상호작용 요소 cursor pointer 설정
  app/[teamId]/(index)/GroupHeader.tsx
  app/[teamId]/(index)/GroupMemberCard.tsx
  app/[teamId]/(index)/GroupTaskList.tsx
Labels: 🎨 Markup

#334 #333 주반복 최소1개이상선택 및 캘린더 외부클릭시 닫힘기능
  components/DateTimePicker/DatePicker.tsx
  components/modal/AddTask.tsx
  hooks/useToggle.tsx
Labels: 🐞 BugFix

#332 #331 사이드바 및 할일 추가 버튼 icon 수정
  app/[teamId]/tasklist/page.tsx
  components/SideNavigation/SideNavigation.tsx
Labels: 🎨 Markup

#322 #321 할 일 완료 여부 변경 관련 기능 구현
  app/[teamId]/tasklist/TaskDetail.tsx
  app/[teamId]/tasklist/TaskListWrapper.tsx
  app/myhistory/page.tsx
  components/DropDown.tsx
  components/TaskCard/TaskCard.tsx
  components/TaskCard/TaskCheckbox.tsx
  stories/TaskCard.stories.tsx
  types/taskCard.type.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Markup

#337 ✨ 게시글 상세 댓글 작성 시 실시간 댓글 수 업데이트
  app/boards/[articleId]/CommentContainer.tsx
Labels: 🔨 Refactor

#338 #335 랜딩 아이템 리팩토링
  app/(auth)/layout.tsx
  app/page.tsx
  components/Landing/LandingCard.tsx
  components/Landing/LandingCardItemsFirst.tsx
  components/Landing/LandingCardItemsSecond.tsx
  components/Landing/LandingCardItemsthird.tsx
  components/Landing/LandingCardList.tsx
  public/images/landing/img-LandingCard-1.png
  public/images/landing/img-LandingCard-2.png
  public/images/landing/img-LandingCard-3.png
Labels: 🎨 Markup

#339 QA 2차 - 할 일 상세 수정
  app/[teamId]/tasklist/TaskCommentWrapper.tsx
  app/[teamId]/tasklist/TaskDetail.tsx
  components/TaskCard/TaskCard.tsx
  components/ui/drawer.tsx
  public/images/icon-complete copy.svg
Labels: 🔨 Refactor, 🎨 Markup

#341 💄 랜딩페이지 애니메이션 적용 및 자유게시판, 팀 리스트 케러셀 인디케이터 추가, 수정
  app/[teamId]/(index)/GroupReportContent.tsx
  app/boards/BestArticleList.tsx
  app/page.tsx
  components/ArticleCard/ArticleCard.tsx
  components/Indicators.tsx
  components/Landing/LandingCard.tsx
  styles/base.css
Labels: 🎨 Markup

#348 #345 팀장 멤버 카드의 드롭다운 제거
  app/[teamId]/(index)/GroupMemberCard.tsx
Labels: 🎨 Markup

#349 #346 팀페이지의 할 일 목록을 요청 시 undefined가 groupId로 전달되는 문제 해결
  app/[teamId]/(index)/page.tsx
Labels: 🐞 BugFix

#350 #347 팀페이지 더보기 기능 구현
  app/[teamId]/(index)/GroupTaskListWrapper.tsx
  app/[teamId]/(index)/page.tsx
Labels: ✨ Feature

#352 랜딩 애니메이션 모바일 적용 및 메타태그 추가
  app/[teamId]/tasklist/TaskDetail.tsx
  app/[teamId]/tasklist/page.tsx
  app/boards/ArticleList.tsx
  app/layout.tsx
  app/page.tsx
  components/Empty/Empty.tsx
Labels: 🎨 Markup

#356 📝 README 작성
  README.md
Labels: 📃 Docs

#354 📝 댓글 컴포넌트 수정 시 textarea focus 적용
  components/Comment/Comment.tsx
  types/inputField.type.ts
Labels: ✨ Feature

#363 🔨 oauthForm 컴포넌트 ref 제거
  app/(auth)/login/page.tsx
  components/OauthForm.tsx
Labels: 🐞 BugFix

#367 #358 네비게이션 드롭다운에 선택된 팀의 프로필 이미지 표기
  components/NavigationGroupDropdown/DropdownAddGroup.tsx
  components/NavigationGroupDropdown/DropdownTab.tsx
  components/NavigationGroupDropdown/NavigationGroupDropdown.tsx
  components/layout/Header/HeadersGnb.tsx
Labels: 🎨 Markup

#366 #357 프로필 컴포넌트 이미지 리사이즈 및 가운데 정렬
  components/Profile/Profile.tsx
Labels: 🐞 BugFix

#368 #359 유저 이메일로 팀 멤버 추가하기 기능 구현
  app/[teamId]/(index)/AddMemberModal.tsx
  app/[teamId]/(index)/GroupMemberList.tsx
  app/[teamId]/(index)/InvitaionLinkModal.tsx
  app/[teamId]/(index)/InviteMemberModal.tsx
  app/[teamId]/(index)/page.tsx
  components/modal/InviteMember.tsx
  stories/GroupMemberList.stories.tsx
  stories/modal.stories.tsx
Labels: ✨ Feature

#370 #369 로그인/회원가입 페이지 리다이렉트 경로 수정
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
Labels: 🐞 BugFix

#365 💄 할 일 카드, 할 일 상세 시간 제거
  app/[teamId]/tasklist/TaskDetail.tsx
  components/TaskCard/TaskCard.tsx
Labels: 🎨 Markup

#361 #360 폰트 옵션 변경 & container 마진탑 패딩탑으로 재수정
  app/(auth)/layout.tsx
  app/layout.tsx
  app/myhistory/page.tsx
  app/mypage/page.tsx
  app/page.tsx
  components/Landing/LandingCard.tsx
  components/layout/Container.tsx
  components/layout/Header/Headers.tsx
Labels: 🐞 BugFix, 🎨 Markup

#372 🔨 세션 상태 조건 추가(디버깅을 위해 console.log 추가)
  app/(auth)/login/page.tsx
  components/OauthForm.tsx
Labels: 🐞 BugFix

#374 🐛 카카오 로그인 후 강제 로그인페이지로 리다이렉트
  hooks/useKakao.ts
Labels: 🐞 BugFix

#376 🔨 일반 로그인 리다이렉트 수정
  app/(auth)/login/page.tsx
  components/Landing/LandingCard.tsx
Labels: 🐞 BugFix

#378 스켈레톤 이미지 배치 코드 수정
  app/myhistory/page.tsx
Labels: 🐞 BugFix

#380 #379 QA 사항 반영
  app/[teamId]/(index)/GroupHeader.tsx
  app/[teamId]/(index)/page.tsx
  app/[teamId]/tasklist/page.tsx
Labels: 🐞 BugFix, ✨ Feature
